print("Personal Information")
name = input("What is your name? ")
age = input("How old are you? ")
number = input("what is your phone number? ")
email = input("What is your emial? ")
current_school = input("What is your current school? ")
previous_school = input("What is your previous school? ")
name_father = input("What is your father's name? ")
name_mother = input("What is your mother's name? ")
number_parent = input("What is one of your parents number? ")
address = input("Where do you live? ")

print("Name:", name)
print("Age:", age)
print("Phone Number:", number)
print("Email: ", email)
print("Current School:", current_school)
print("Previous School:", previous_school)
print("Name of Father:", name_father)
print("Name of Mother:", name_mother)
print("Number of Parent:", number_parent)
print("Address: ", address)